### ISSUE TITLE
NC or NURBS meshes

### ISSUE THREAD

**Issue by varchasgopalaswamy** [CEED/Laghos#102]
Hi,

I am a little new to this, so apologies if these are naive questions. My understanding is that MFEM generally supports nonconforming or NURBS meshes. However, it looks like all the meshes used by laghos (either generated on the fly or in the data/ directory) are conforming and in an H1 basis. 

With regards to non-conforming meshes - the experimental AMR version (which should be NC, right?) does not appear to support partial assembly. Is this a general issue with NC meshes (i.e. that they do not support partial assembly)? 

 With regards to NURBS meshes, while there doesn't seem to be any explicit usage of it right now, since it's just a different basis for the nodes grid function, it would _seem_ that they should be compatible with laghos. Is this accurate, or are there any gotchas I ought to be aware of? 

Thanks!

**Comment by vladotomov** [comment]
Hi @varchasgopalaswamy,

> Is this a general issue with NC meshes (i.e. that they do not support partial assembly)?

Partial assembly can be combined with NC meshes, but we haven't implemented this in Laghos yet.

>With regards to NURBS meshes, while there doesn't seem to be any explicit usage of it right now, since it's just a different basis for the nodes grid function, it would seem that they should be compatible with laghos. Is this accurate, or are there any gotchas I ought to be aware of?

Laghos can be used with NURBS meshes. Once they are read, they get converted to the MFEM's internal representation (H1 basis) of the chosen order.

Best,
Vladimir

**Comment by varchasgopalaswamy** [comment]
Vladimir,

Thanks for the clarifications! Two more questions, if you dont mind:

1) Is there a technical reason why full assembly is used in 1D? Is it for demonstration purposes of full assembly or is there some reason partial assembly won't work in 1D? It _seems_ like it ought to work if the appropriate kernels are added to laghos_assembly.cpp, but I wasn't sure if I missed something in the documentation. 

2) If I wanted to use a different EOS, it would simply be a matter of modifying QUpdateBody, correct? 

Thanks!
Varchas

**Comment by vladotomov** [comment]
Hi Varchas,

1. It would work, but on element level, full assembly and partial assembly are the same thing in 1D. There might be small performance differences if one does matrix-free solve for the linear systems or not.

2. Yes, you only need to update the pressure calculation.

Best,
Vladimir
