### ISSUE TITLE
Definition of Q1D

### ISSUE THREAD

**Issue by varchasgopalaswamy** [CEED/Laghos#103]
Hi,

I had a doubt about how the number of quadrature points are defined, since there are two definitions that I'm not sure are always the same. 

If I understood it right, in `Rho0DetJ0Vol`, Q1D is defined by using the integration order for the problem, assuming it is used for a line segment, and then getting the number of quadrature points. 

In `LagrangianHydroOperator` and I think all its members, Q1D is defined by `int(floor(0.7 + pow(ir.GetNPoints(), 1.0 / dim)))`, which I'm not sure I understand. I'm guessing the N-root part is taking the number of quadrature points in the N-dimensional space and taking the N-root to get the effective number of quadrature points in 1D. What then is the purpose of adding 0.7 and taking the floor? Alternatively, why not use the same definition as in `Rho0DetJ0Vol`? 

Thanks,
Varchas

**Comment by vladotomov** [comment]
Hi Varchas,

The 0.7 and the `floor` are used to avoid round-off errors. The two formulas should always be equivalent for tensor elements, (which is when Q1D is used).

Vladimir

**Comment by varchasgopalaswamy** [comment]
Understood - Thanks!
