### ISSUE TITLE
R-Z coordinates with partial assembly

### ISSUE THREAD

**Issue by varchasgopalaswamy** [CEED/Laghos#106]
Hi,

I was trying to get an idea of what it would take to add an r-z coordinate system to laghos. From [this paper](https://computing.llnl.gov/projects/blast/CF-12.pdf), it looks like modifications need to happen to 

- `det(J)(0)rho(0)` (eq. 16) 
- The artificial viscosity 
- The force matrix (eq. 24) 
- Both mass matrices (eq. 20 and 23) 

 where the modifications appear to mostly be multiplications/divisions by `r`. What's the right way to get the coordinate information into the partial assembly kernels? I think the following code should be right, but I wanted to make sure I understood what's going on correctly:

```
const mfem::QuadratureInterpolator* coord_interpolator = H1.GetQuadratureInterpolator(integration_rule);
mfem::Vector coordsQ(NQ*NE*DIM); 
coord_interpolator->Values(coord_gridfunction, coordsQ);
auto X = mfem::Reshape(coordsQ.Read(), NQ, NE, DIM);
```

and then I could access the radius as `double radius = X[quadrature_point,element,0]` at some quadrature point of some element. 

Thanks,
Varchas

**Comment by vladotomov** [comment]
Hi Varchas,

Yes that sounds mostly right. The modifications in the force matrix and artificial viscosity are more involved as they require an extra term. And yes, you can get the coordinates at the quadrature points from the `QuadratureInterpolator` applied to the `x` function that represents positions.

Vladimir
