### ISSUE TITLE
blast wave propagation

### ISSUE THREAD

**Issue by Janssen-Yang** [CEED/Laghos#133]
Hi!
I wonder if this software can be used to simulate blast wave propagation in urban environment?
Thanks in advance！

**Comment by vladotomov** [comment]
Generally yes, up to the treatment of the wall boundary conditions. Currently Laghos can only do walls that are parallel with the x/y/z planes. There are plans to implement general (including curved) surfaces in the next month or two.

**Comment by Janssen-Yang** [comment]
Thanks for your response. Have a nice day!
