### ISSUE TITLE
Other Equation of State in Laghos

### ISSUE THREAD

**Issue by Liu0813** [CEED/Laghos#137]
Hi, 
I tried to modify the equation of state in Laghos, but encountered some trouble. Taking Sod shock tube as an example, when using the original equation of state for ideal gas, the result is correct. But when modified to the [NASG equation](https://aip.scitation.org/doi/10.1063/1.4945981) for liquid water, there are a lot of numerical oscillations, like the following images.

![image](https://user-images.githubusercontent.com/30075822/110481543-a611fd00-8122-11eb-831e-94d5a8f7521f.png)

I don't quite understand why? I am not sure if Laghos is suitable for EOS with real parameters. Looking forward to your response.

Thanks,
Liu

**Comment by vladotomov** [comment]
Laghos can be used with different EOS, but the code should be modified at a few places, because it assumes ideal gas. Some parts of the code also assume that `gamma` is constant in each element.

It's difficult to say what's wrong from these pictures. Is this the initial condition or an evolved solution? Why does the energy look as if it hasn't changed?

I'd recommend to start with running the problem in 1D.

**Comment by Liu0813** [comment]
Hi, @vladotomov,
Thank you for your suggestion.  To test different EOS, I try to solve the water shock tube problem in the following publication:
> Chandran, J., & Salih, A. (2019). A modified equation of state for water for a wide range of pressure and the concept of water shock tube. Fluid Phase Equilibria, 483, 182-188.

The initial problem setup is asshown in the following figure, where inside a 3m long tube, a diaphragm separates liquid water under very high pressure from water at a comparatively low pressure.  The liquid water is treated as compressible fluid by the relevant EOS, here the Noble-Abel Stiffened-Gas equation of state is used. 

![image](https://user-images.githubusercontent.com/30075822/110574452-173fc780-8198-11eb-8fc5-3dbbbd8f466f.png)

In order to solve this problem, the source file `laghos_solver.cpp` is modified, as follows. The calculation of EOS
https://github.com/CEED/Laghos/blob/95f2b9d748146d94ab70086329a6c6f814767379/laghos_solver.cpp#L1007-L1008
is changed into

```c++
const double P = (gamma - 1.0) * (E + 1177788) / (1/R - 6.72125e-4) - gamma * 6.2178e8;  
const double S = sqrt(gamma * (1/R)*(1/R) * (P+6.2178e8)/(1/R-6.72125e-4));
```
Correspondingly, the initial condition is set in function `rho0`, `gamma`, `v0`, `e0`, and the modified code snippet is listed.

```c++
double rho0(const Vector &x)
{
   return (x(0) < 2.0) ? 1010 : 997;
}

double gamma(const Vector &x)
{
      return 1.19; 
}

void v0(const Vector &x, Vector &v)
{
      v = 0.0; 
}

double e0(const Vector &x)
{
   return 3610*300+(1/rho0(x)-6.72125e-4)*6.2178e8-1177788;
}
```

The result is basically reasonable, but there are many non-physical oscillations, like the following figures. Under this initial condition, the amplitude of the wave is relatively small, so the energy change is not obvious.

![image](https://user-images.githubusercontent.com/30075822/110574018-46a20480-8197-11eb-8db8-07fab68a0e1b.png)

According to your advice, I have also run this problem in 1D, and non-physical oscillations are not very obvious, like the following figures.

![image](https://user-images.githubusercontent.com/30075822/110570210-874a4f80-8190-11eb-840b-49d5f1007ecd.png)

By the way,  if the initial density in left region is increased, the effect of non-physical oscillations will also be reduced.

**Comment by vladotomov** [comment]
Are you running with `-pa` or `-fa`? For the 1D test you're surely running `full assembly`, because the code forces it in 1D.

The full assembly pressure calculation is in `ComputeMaterialProperties()`, see [here](https://github.com/CEED/Laghos/blob/95f2b9d748146d94ab70086329a6c6f814767379/laghos_solver.hpp#L157).
Update that and let me know if the results are better.

**Comment by Liu0813** [comment]
Hi, @vladotomov 
The above results in 1D and 2D are obtained using `-fa` mode. For 1D test, pressure and sound speed is calculated in `ComputeMaterialProperties()`, and I have modified it into my EOS. In addition, I also try the `-pa` option in 2D problem, and the result is similar.

**Comment by vladotomov** [comment]
Good, then the EOS calculations are probably correct.
The 1D test looks reasonable. Some oscillations are expected, e.g., for the density and energy in the contact discontinuities. Is it converging to the reference solution under refinement?

**Comment by Liu0813** [comment]
Hi, @vladotomov
I have tested this problem at different levels of refinement. In the 1D case, as the mesh is refined, the oscillation near the contact discontinuity will decrease, and the result will converge to the reference solution. However, in the 2D case, the refinement of the mesh will cause the oscillation to be worse.

**Comment by vladotomov** [comment]
Yes surely there is some setup issue in 2D.

**Comment by vladotomov** [comment]
Are you able to run the 1D problem in 2D? This may show some inconsistencies.

**Comment by Liu0813** [comment]
I try to run the 1D problem in 2D. The calculation area is divided into 60 elements in the x direction, and there is only one elements in the y direction. It is shown that the size of element in y direction have effect on the result. When dy=0.05 (i.e. dy=dx), the numerical oscillations near the contact discontinuity are very large, as the following figure shown.
![image](https://user-images.githubusercontent.com/30075822/110897201-f9a96400-8337-11eb-9eb2-089ad70e2552.png)

But when dy=0.1(or larger), the oscillation will decrease and have little effect on the result.
![image](https://user-images.githubusercontent.com/30075822/110897219-03cb6280-8338-11eb-91e7-ffb8c2c7a121.png)

**Comment by vladotomov** [comment]
I can't guess what's wrong, but you can use these differences to debug the issue with 2D. To get equivalent 1D and 2D behavior, make sure that the boundary attributes on the 2D mesh are correct, and the initial time steps are the same (you'll have to edit the code to force this for the 2D runs).

**Comment by Liu0813** [comment]
This problem has been solved. It should be that the default time step is not suitable. When the "cfl" number is decreased, the numerical oscillations will vanish.
