### ISSUE TITLE
"spack install laghos"  on LLNL quartz with gcc/8.3.1 is failing

### ISSUE THREAD

**Issue by maheshrajan5** [CEED/Laghos#141]
Hi:  I am Mahesh Rajan ( rajan2@llnl.gov) supporting COE CI/CD effort.

Want to get your help with building Laghos on LLNL Quartz.
My attempt today ( 3/22/2021) with "spack install laghos" fails with the following error messages.
     7     cd .; /p/lustre1/mrajan/spack/opt/spack/linux-rhel7-broadwell/gcc-8.
           3.1/openmpi-4.0.5-6nhmalbbnbdxc2qmun5yztjoud3e7vnf/bin/mpic++ -O3 -s
           td=c++11 -I/p/lustre1/mrajan/spack/opt/spack/linux-rhel7-broadwell/g
           cc-8.3.1/mfem-4.2.0-6eq367cxc55rdkuh6xtg4j7tmqbah4m2/include -I/p/lu
           stre1/mrajan/spack/opt/spack/linux-rhel7-broadwell/gcc-8.3.1/hypre-2
           .20.0-xiuhkbvqpuwkkogpsrqxq4ggzo76re5w/include -I/p/lustre1/mrajan/s
           pack/opt/spack/linux-rhel7-broadwell/gcc-8.3.1/metis-5.1.0-bdz23neyy
           vkgzqxjzpildqzfd2skem3v/include -I/p/lustre1/mrajan/spack/opt/spack/
           linux-rhel7-broadwell/gcc-8.3.1/zlib-1.2.11-c7zv5ftnxfe4h3237t42mshb
           rwd4ecv7/include -I/p/lustre1/mrajan/spack/opt/spack/linux-rhel7-bro
           adwell/gcc-8.3.1/mfem-4.2.0-6eq367cxc55rdkuh6xtg4j7tmqbah4m2/include
           /mfem -c laghos_solver.cpp
     8     laghos.cpp: In function 'int main(int, char**)':
  >> 9     laghos.cpp:525:39: error: no matching function for call to 'mfem::Fu
           nctionCoefficient::FunctionCoefficient(<unresolved overloaded functi
           on type>)'
     10        FunctionCoefficient mat_coeff(gamma);
     11                                           ^

FYI, my attempts to build Laghos with instructions at  Github have also been unsuccssful with Module Intel/19.0.4 and with Module gcc.  If you have new instructions on successful build ( directly, not with spack)  I would appreciate a tested build process that works on LLNL CTS system like Quartz.  
Thanks

**Comment by v-dobrev** [comment]
There was a change in MFEM v4.2 that causes the above error (PR https://github.com/mfem/mfem/pull/1661) and I think the Laghos source was updated for that. I think the following specs should work: `laghos@master` or `laghos ^mfem@4.1.0`.

**Comment by v-dobrev** [comment]
We should probably update https://github.com/spack/spack/blob/364b359c6830e6b46b822c4a716cac284fada363/var/spack/repos/builtin/packages/laghos/package.py#L35
to be (use mfem == 4.1.0 instead of mfem >= 4.1.0 with laghos 3.0)
```
    depends_on('mfem@4.1.0', when='@3.0')
```
