### ISSUE TITLE
Laghos in a workflow?

### ISSUE THREAD

**Issue by vsoch** [CEED/Laghos#174]
Hi! I was wondering if you have any example workflows that use Laghos that are beyond a single command (e.g., the mpirun examples at the bottom of the repository). We are looking for something that has a bit of complexity in terms of workflow steps. Thanks!

**Comment by vladotomov** [comment]
Hi @vsoch,

Not sure, could you give an example of what you need?

**Comment by vsoch** [comment]
It could be anything from running a few steps (or more generally a workflow with several components) to having a service like a database or task queue alongside. Basically - anything more complex than a simple, single command to submit!

**Comment by vladotomov** [comment]
I don't know of such workflows with _`Laghos`_. Maybe @kmittal2 has such workflows, but with _`Remhos`_, related to his machine learning explorations.

**Comment by vsoch** [comment]
Thanks - so there is no small public collection of workflows using this tool?

**Comment by vladotomov** [comment]
Actually there's the autotest workflow, see [here](https://github.com/CEED/Laghos/actions/runs/2387946552/workflow).

**Comment by vsoch** [comment]
This should be good to get me started! And if @kmittal2 has something more complex to share that would be great. I’ll do some work this weekend and update you here. Thank you and happy Friday!

**Comment by kmittal2** [comment]
Hi @vsoch, unfortunately I do not have anything more complex to share.

**Comment by vladotomov** [comment]
@vsoch I'm closing this for now, let us know if we can help more.

**Comment by vsoch** [comment]
Heyo! I wanted to give you updates - I have a build in a container alongside flux, and it looks like the example is running OK!

![image](https://user-images.githubusercontent.com/814322/226503795-34b577b3-e33a-476f-a20a-c1f9d888c6aa.png)

and the tests passed I think:

![image](https://user-images.githubusercontent.com/814322/226503953-2666a42f-0e88-4790-bcd1-ff3d5fbd0ea4.png)

The results look like this:

```
# cat RESULTS.dat 
step = 0339, dt = 0.000702, |e| = 4.9695537349e+01
step = 1041, dt = 0.000121, |e| = 3.3909635545e+03
step = 1154, dt = 0.001655, |e| = 4.6303396053e+01
step = 0560, dt = 0.002449, |e| = 1.3408616722e+02
step = 0413, dt = 0.000470, |e| = 3.2012077410e+01
step = 2872, dt = 0.000064, |e| = 5.6547039096e+01
step = 0858, dt = 0.000474, |e| = 5.6691500623e+01
step = 0776, dt = 0.000045, |e| = 4.0982431726e+02
```
The automated build is happening now, and once I have the container in a registry it should be fairly trivial to test with the Flux Operator. I will update here again when that is done! In the meantime if you find any more complex workflows please let me know! We are selecting three to include in a paper on the Flux Operator and still in the learning / testing phase for various tools at the lab.

**Comment by vladotomov** [comment]
Sounds great, feel free to reopen if we can help.

**Comment by vsoch** [comment]
okay done! I wound up taking out the command from `make tests` and giving it directly to flux, and that seemed to go faster. I was also very happy to see that command, because it looks like there are some parameters we could tune to test this at different scales.

![image](https://user-images.githubusercontent.com/814322/226512410-3d1d2466-1558-439b-94e8-7335bb0fe77d.png)

We will have a minicluster.yaml example with laghos merged a bit later tonight. 

And I really appreciate how easy this was to get working - going through all the actions that you use to install mfem/hypre/etc.  was probably the hardest part - a container build that shows them all in one place would do wonders! If you ever need to point someone at a container, this build likely isn't perfect, but it got the job done (as shown above). It starts on top of a flux base built with conda (which I've done since a lot of projects like to do ML stuffs), which likely if you wanted to roll a custom build wouldn't be necessary (it makes the image quite a bit larger!) For keeping a record in this issue, here is the directory with the Dockerfile: https://github.com/rse-ops/flux-hpc/tree/main/laghos-demos. We also have an automated build, here: https://github.com/rse-ops/flux-hpc/pkgs/container/laghos-demos. The demo for the Flux Operator is just a yaml file that uses that image and defines the entrypoint, etc (as shown in the picture above).

Thank you again! We will definitely ping you if we have any more questions! And please ping me for any simulations / workflows / something the lab is interested in that could be run in the Flux Operator, even if they aren't containerized. I'm pretty good at that bit, and I'm trying to port / test as many things as I can get my hands on. :laughing:
