### ISSUE TITLE
getting a makefile error when trying to build laghos-raja 

### ISSUE THREAD

**Issue by ashwin2509** [CEED/Laghos#18]
I want to run Laghos with Raja. 
However I am not able to build the application. After a host of warnings, I see these errors. 

```
make[2]: *** [makefile:344: laghos] Error 252
make[2]: Leaving directory '/g/g92/ashwin/Laghos1/Laghos' 
make[1]: *** [makefile:340: all] Error 2
make[1]: Leaving directory '/g/g92/ashwin/Laghos1/Laghos'
make: *** [makefile:185: raja] Error 2
```

I would really appreciate any help on this. 
Thank you.

**Comment by camierjs** [comment]
Building with RAJA+CUDA and with MFEM reverted of #480 was ok.
