### ISSUE TITLE
A quick question

### ISSUE THREAD

**Issue by sungho91** [CEED/Laghos#185]
Hi all,

I was wondering why Laghos takes negative force; `rhs.Neg()`, which is `-F` in `SolveVelocity`. 
There is no reason to do that, I think, because F = ma. However, if I take it out, it does not run correctly. 
So, there is a certain reason for taking a negative there. 
Does anyone know about it?

Best,

Sungho

**Comment by vladotomov** [comment]
See the paper listed at the start of the README, the code mostly follows those equations.

V. Dobrev, Tz. Kolev and R. Rieben
[High-order curvilinear finite element methods for Lagrangian hydrodynamics](https://doi.org/10.1137/120864672)
SIAM Journal on Scientific Computing, (34) 2012, pp. B606–B641.
