### ISSUE TITLE
Incorrect assertion in laghos_assembly.cpp

### ISSUE THREAD

**Issue by ilagunap** [CEED/Laghos#22]
On laghos_assembly.cpp (line 124 in raja-dev branch):

An array is compared against an integer. Compiling with Clang reports this error:

```
/usr/workspace/wsa/laguna/laghos_cuda/laghos/Laghos/laghos_assembly.cpp:124:20: 
error: ordered comparison between pointer and zero ('int *' and 'int')
   assert(ess_tdofs>0);
```

I believe the solution is `assert(ess_tdofs.Size()>0);`

**Comment by tzanio** [comment]
@camierjs is this still an issue?
