### ISSUE TITLE
Getting velocity vectors 

### ISSUE THREAD

**Issue by cjoycd** [CEED/Laghos#43]
Dear all,

Can someone please help me to tell me the function/class to get the physical velocity vectors (say Vx and Vy in 2D case) at eachquadrature points ? I need this especially in the module "laghos_solver.cpp" -- in update quadrature module .

This is to add necessary additional terms for axisymmetric conversion apart from the modifications done in the MFEM library in the bilinear integration. As a first step It
will be tried in full assembly case . Thanks

 Thanks in advance..

**Comment by vladotomov** [comment]
Hi cjoycd,

Take a look at the different variants of GridFunction::GetValue / GetValues / GecVectorValue / GetVectorValues.

Vladimir

**Comment by cjoycd** [comment]
Thanks Vladimir,

I m using the GetVectorValues() and it's seems to be working ..

Thank you very much

Regards
