### ISSUE TITLE
Cylindrical co-ordinate implementation with FA

### ISSUE THREAD

**Issue by cjoycd** [CEED/Laghos#45]
Dear All,

Implemented cylindrical co-ordinate implementation with FA. It also include some modifications in MFEM/fem/bilininteg.cpp & MFEM/fem/bilininteg.hpp files.  Please find attached files and some one please comment is it worth to incorporate in the actual code. 

[laghosRZ.zip](https://github.com/CEED/Laghos/files/2995226/laghosRZ.zip)
[MFEM_RZ.zip](https://github.com/CEED/Laghos/files/2995228/MFEM_RZ.zip)

Regards
--Sijoy C. D.

**Comment by vladotomov** [comment]
Hi Sijoy,

We're happy to hear that you were able to use Laghos and extend it to RZ problems. This extension was one of the functionalities we were considering for Laghos, but decided to not include it in the baseline version, as we prefer to preserve the low complexity of the mini-app. We will consider your code if we decide to add RZ capability of Laghos in the future. Feel free to create a branch with your implementation (branches in GitHub are our preferred workflow).

Can you give some more details about the MFEM changes? Feel free to issue a pull request with your changes, if you think those are general finite element operations that will be useful as part of the library.

Thanks,
Vladimir

**Comment by cjoycd** [comment]
Dear Vladimir,

OK, Thank you for your mail. The changes in MFEM & Laghos are relatively
simple.
In particular, I have added few functionalities in the bilininteg.cpp
module.

These changes are only in bilininteg.cpp & interlining.hpp files (attached
herewith).
1) void MassIntegratorRZ::AssembleElementMatrix..   --- For Mass
integration with "r" factor multiplied.
     This is basically modified routine of
MassIntegrator::AssembleElementMatrix... with the "r" factor in the
integration included.
2) void VectorMassIntegratorRZ::AssembleElementMatrix... -- For vector mass
integration in RZ co-ordinate.
     This is basically similar to void
VectorMassIntegrator::AssembleElementMatrix with the "r" factor in the
integration included.
And, in the "interlining.hpp" these are constructed/defined.

Thanks & Regards,
-----------------------------------------------------------
Sijoy C. D.
Asst. Professor,
Homi Bhabha National Institute (HBNI),
Mumbai, India
------------------------------------------------------------
