### ISSUE TITLE
'laghos' cores when run against 'box01_hex.mesh' with perfect cube of ranks

### ISSUE THREAD

**Issue by cdm-work** [CEED/Laghos#51]
Following the guidance from the `README.md`, I tried to run `laghos` with the 'box01_hex.mesh' data file on 64 ranks.  It resulted in a segfault, with a core file created.  Investigating this, I found that if the value of ranks was a perfect cube such as 27, 64 or 125, it would segfault (with the exception of '8'; that works).  Set the number of ranks to be one more or less than the perfect cube value, and it works without issue.

Here is an example of the command used:
`srun --ntasks=27 laghos -p 3 -m box01_hex.mesh -rs 1 -tf 3.0 -pa`

I've only observed this issue with the 'box01_hex.mesh' input file; all other data files seem to work without issue for any number of ranks.

I built Laghos against hypre 2.7.0, metis 5.1.0, and mfem 4.0.

**Comment by vladotomov** [comment]
Hi @cdm-work,
Thank you for reporting this. The code was trying to setup a uniform mesh partitioning over the MPI tasks, but the box01 mesh was not appropriate for that. I switched the default behavior to using METIS. It should be resolved in the master branch now.

**Comment by cdm-work** [comment]
I built Laghos with the recent changes, and I'm not hitting the issue any longer.  So I'm willing to consider this fixed.
