### ISSUE TITLE
L2 space for the energy variable discretization

### ISSUE THREAD

**Issue by avinmoharana** [CEED/Laghos#58]
We are trying to incorporate the ability to do higher order conforming mesh adaptation for the LAGHOS problem by using the PUMI framework. Is the discretization of the energy variable in the L2 space a requirement for the solver? Our approach so far has been to express the solution variables in the Bernstein basis to ease the solution transfer onto the curved adapted mesh. Is the piece-wise constant energy values from the previous time step used in a coupled fashion to solve for the next step? We would like to understand the necessity for the chosen discretization and the details of the time update step before moving forward.

**Comment by v-dobrev** [comment]
Yes, the energy space has to be discontinuous. The basis is not that important for the method, so one can use the DG Bernstein basis for the energy space too.

To do spatial adaptivity, it is probably simplest to perform that with a fixed simulation time: after a full time step, take the mesh and the fields, perform mesh refinement and/or de-refinement, interpolate the fields, rebuild the spatial operators for the new mesh and then continue. The adaptivity step can be triggered in various ways, e.g. simply at every k-th time step, or using more advanced "adaptivity trigger" that will depend on the current discrete state.
